#  Мой образ был протестирован на двух операционных системах (Ubuntu и AWS Linux)
# , поэтому плейбук предназначен для обеих ОС.
- name: Install Docker and deploy container from Docker Hub
  hosts: all
  become: true  # for sudo
  tasks:
    # 1. Устанавливаем зависимости 
    - name: Install Docker dependencies 
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG apt Key 
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Add Docker Repository 
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu  lunar stable"
        state: present


    - name: Add Docker repository 
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu lunar  stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == "Debian"

    # 5. Устанавливаем Docker (для CentOS/RHEL)
    - name: Install Docker (CentOS)
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"

    # 6. Убедимся, что Docker запущен
    - name: Ensure Docker is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "gmunira/web_app_image:latest"
        source: pull
      become: true

    - name: Run Docker container from pulled image
      docker_container:
        name: my_application_container
        image: gmunira/web_app_image:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"  # Пример переноса портов, если нужно
      register: container_status
      ignore_errors: yes

    - name: Create container if doesn't exist
      docker_container:
        name: my_application_container
        image: gmunira/web_app_image:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
      when: container_status.failed
