name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest 

    steps:
      # 1.clone repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Вход в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Сборка Docker-образа
      - name: Build Docker image
        run: |
          cd app
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web_app_image:latest -f Dockerfile .

      # 5. Загрузка Docker-образа в Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/web_app_image:latest

      # 6. Удаление существующего контейнера 
      - name: Remove existing Docker container
        run: |
          docker container rm -f web_app_container || true

      - name: Create SSH key file
        run: |
          echo "$ANSIBLE_PRIVATE_KEY" > .ansible_key
          chmod 600 .ansible_key

      # 7. Выполнение Ansible playbook для деплоя
      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy_docker_app.yml
          directory: deployment/
          key: ${{ secrets.SSH_PRIVATE_KEY }}  
          inventory: |
            [aws]
            ${{ secrets.REMOTE_HOST }} ansible_ssh_user=${{ secrets.ANSIBLE_SSH_USER }}  
          options: |
            --verbose  


